### ISSUE TITLE
Buffer.slice does not work as expected

### ISSUE THREAD

**Issue by rj-xy** [brunch/node-browser-modules#4]
Using Chrome Version 64.0.3282.140 (Official Build) (64-bit)

if I have a variable myBuffer which is a Uint8Array(64):
When: `myBuffer.slice(0,32)` returns a Uint8Array(64), when it should be Uint8Array(32).

This is a significant problem when using bitcoinjs-lib, the following returns the error "_Private key must be less than the curve order_"
`var root = bitcoin.HDNode.fromSeedHex('dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd');`

The following PR should fix the issue:
https://github.com/brunch/node-browser-modules/pull/2

The current workaround is to update the package-lock.json in my project so that **Buffer** version 5.0.8 is used instead of 4.3.1

**Comment by paulmillr** [comment]
Done.
