### ISSUE TITLE
Dependencies out-of-date

### ISSUE THREAD

**Issue by rj-xy** [brunch/node-browser-modules#5]
All dependencies are out of date, this has a direct effect on Brunch, since it uses this NPM package

**Comment by yoursunny** [comment]
This needs to be fixed. Currently, I cannot import [cbor](https://www.npmjs.com/package/cbor) package because it uses `Buffer.from("..", "hex")` that was not supported on old "buffer" package.

**Comment by paulmillr** [comment]
Done.
